query schedule {
  conferences {
    nodes {
      acronym
    }
  }
  conference: conferenceByAcronym(acronym: "36c3") {
    acronym
    title
    start: startDate
    end: endDate
    rooms {
      nodes {
        name
      }
    }
    events {
      totalCount
      nodes {
        id: localId
        guid
        url
        dayIndex
        roomName
        logo
        startDate
        startTime
        duration: durationTime
        slug
        title
        subtitle
        track 
        eventType
        language
        abstract
        description
        recordingLicense
        doNotRecord
        persons {
          nodes {
            guid
            publicName
          }
        }
        links {
          title
          url
        }
        attachments {
          title
          url
        }
      }
    }
  }
}

